# Generated by Django 3.2.22 on 2023-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='money',
            field=models.CharField(default='', max_length=30),
        ),
    ]
